Shih-Yu Chang: HW1
=====================================================
1) Step1: Connect to the GEO database 
```{r}
library(GEOmetadb)
geo_con<-dbConnect(SQLite(),'GEOmetadb.sqlite')
```

Step2: find the data
```{r}
dbGetQuery(geo_con, "SELECT gse.title, gse.gse, gpl.gpl, gpl.manufacturer,gpl.description 
FROM (gse JOIN gse_gpl ON gse.gse=gse_gpl.gse) j JOIN gpl ON j.gpl=gpl.gpl 
WHERE gpl.Title LIKE '%Illumina%' AND gse.contact LIKE '%Institute: Yale %'  AND gse.Title LIKE '%HCV%Illumina%' ;")
```

=====================================================
2) Convert to the data.table

```{r}
library(data.table)
gse_table = data.table(dbReadTable(geo_con, 'gse'))
gpl_table = data.table(dbReadTable(geo_con, 'gpl'))
gse_gpl_table = data.table(dbReadTable(geo_con, 'gse_gpl'))
```

Step2-Querying
```{r}
merge( merge( (gse_table[like(contact,"Institute: Yale")][like(title, "HCV")]), gse_gpl_table, by = "gse",  suffixes = c(".gse_inner",".gse_gpl") ), gpl_table[like(title, "Illumina")], by = "gpl", suffixes = c(".gse", ".gpl") )[,list(title.gse, gse, gpl, manufacturer, description)]

```
